### ISSUE TITLE
Install logging framework and remove all `console.log` from code

### ISSUE THREAD

**Issue by breakpointer** [ethereum-oasis/baseline#101]
## Overview

As a proper system, so I can be compliant with log level support, install a logging framework (like Winston) and remove all usages of the generic console.log. Replace them with appropriate 'info', 'warn', 'error', 'debug' level logging calls.

### Assumptions

- We will use the same logging format across all services
- The logs for HTTP requests vs system calls should be handled
- Log tracing is not required at this point but would be nice
- Log rotation/truncation is out of scope
- Logs should in their own folder and added to gitignore

### Acceptance

Minimum effort is to 
- install logger framework
- remove console.logs and replace the log call with the appropriate level 'info' 'warn' 'debug' etc...
- adjust environment configs to the appropriate log level (e.i. 'debug' in development, 'info' in production) 
- update documentation on how to view access the log files
- adjust logging format for all services such that they are the same.

Ideal logging format is 
[UTC timestamp] [service name] [host] - <logging message>

**Comment by myronrotter** [comment]
I am on it while browsing through the code. May take some days to get everything in log shape. I will use winston as suggested.

**Comment by myronrotter** [comment]
The integration of the customized logger module turnes out to be more difficult than expected. @breakpointer any suggestions on how to integrate the customized logger module into the dockerized setup. Currently, I am struggling to change the docker build context for the services in order to use the local logger module. Anyway, I dont know if this (changing the docker setup) is what receives general consent.

**Comment by breakpointer** [comment]
@myronrotter Thanks for taking a look at this issue! I'm not sure I can picture how you're trying to `change the docker build context for the services in order to use the logger module as a local dependency.` Do you have a branch/fork I could look at?

**Comment by myronrotter** [comment]
@breakpointer Sure, I have a [branch called logger on my fork](https://github.com/myronrotter/baseline/tree/logger). Currently, I added a first draft of a customized winston logger which should be used as a (local) dependency for any of the microservices, e.g. I started by adding the logger as a (local) dependency to the `zkp` service. Right now, I am trying to integerate the local dependency into the overall build process. So far, I added `/ops/build_logger.sh` similar to any of the services.

AFAIK, in order to use the customized logger module as a dependency for the services, it must be ship into the docker container of the service, i.e. integrated into the `docker-compose` build process and installed via the `dev.Dockerfile`. 
Further, the `context` for the docker-compse build is defined in the `docker-compose.yml` for each of the services such that the logger module is out of scope. E.g. in `radish34` path both logger module and `zkp` service reside, logger is a dependncy of zkp service:
```
 "dependencies": {
    ...
    "radish34-logger": "file:../logger",
    ...
  },
```
and zkp's build context is `/radish34/zkp/` such that logger is out of scope.

I have tried to define the logger module as a data volumn in `docker-compose.yml` and handle the dependency this way such that we do not need to change the docker build context, but unfurtunetly this does not work. I could change the docker build context for each service such that the logger module is in scope, but I dont know if this is what receives general consent/ is the best practise.

Any suggestion on the integration would be helpful or another approach on how to integrate the logger to the setup.
