### ISSUE TITLE
Error registering Buyer or Supplier at http://radish34-ui.docker/

### ISSUE THREAD

**Issue by jeffprestes** [ethereum-oasis/baseline#103]
## Expected Behavior
I don't know I could not see next page

## Actual Behavior
After access http://radish34-ui.docker/ select buyer account and buyer role and try push next button it does not move forward and at JS Console error I got this message:

Warning: An unhandled error was caught from submitForm() Error: Network error: Response not successful: Received status code 400
    at new ApolloError (ApolloError.ts:46)
    at Object.error (QueryManager.ts:255)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at httpLink.ts:184

## Steps to Reproduce the Problem

  1. Start radish
  2. Access http://radish34-ui.docker/
  3. Select Buyer account
 4. At Connect to registry select buyer role
5. Push Next button 

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by Mel-Marsollier** [comment]
Hi Jeff, 

Thanks for pointing out this issue. I had the same problem last week - It should now be resolved given many updates to the repo in the past couple days. I fired up the demo this morning and it went passed the initial page this time around.

I would suggest that you either:

A) Perform  i) git pull origin master, ii) stop && remove the application containers, and iii) rebuild the application.
B) Perform i) complete clean-up of the application docker presence  ii) delete the baseline folder all together, and iii) rebuild the application.

In theory A should work, however because the way that many micro-services were used have changed significantly since last week’s version I would suggest going for B. 

Keep in mind the Read Me changed since last week, for example the demo now runs on http://localhost:3000. I also noticed that building the application this time around required an increase amount of CPUs. My CPUs docker settings are at 12. 

I noticed that the “Supplier1 proposal by id” test as of this morning was failing, so this may impact some of the actions that can be performed in the demo at the moment. 

If you encounter some other issues, let me know, 

Mel

**Comment by jeffprestes** [comment]
Thanks Mel for the heads up message. 
As you got another error I will be waiting baseline team fix all these issues. 
However, as I've mentioned at other issue I opened last week why not use Go or Rust in backend? I work with Ethereum Blockchain since 2016 and full time since 2018 and Node.js always create problems. I strongly encorage the project architect to change the backend stack to avoid issues and to create several docker machines consuming gigabytes.

**Comment by Mel-Marsollier** [comment]
Hi Jeff this is a great question! 

I think like most things it’s a question of comfort with the programing language from the initial members of the dev team who pushed this project forward, and as you mentioned optimization based on the strength of a language. 

As you can see this is meant to be an iterative process, these are great points and something to discuss moving forward. I see value in leaving an active dedicated issue to that question opened, and let you and other members of the Ethereum community provide their opinion and influence the project. It would be interesting to hear from a core engineer to the project on such a thread. I personally wouldn’t be the right person to lead this conversation but I will tune in as I’m interested in knowing the direction that the optimization route will take baseline. 

Feel free to create that separate issue, and it will get the attention of a member of the initial core engineering team. 

I will keep helping you with the set-up and will update you in this thread when I see that the demo runs smoothly and that all features are operational. As of this morning there is still some work to be done to allow successful creation of a PO – the other features should be running well if in the meantime you want to give it a try regardless. 

Thank you Jeff, 

Mel

**Comment by skarred14** [comment]
thanks for raising this issue @jeffprestes . there was a recent change for ease of use of the overall setup. these include removal of dependency on `dotdocker`, and overall orchestration clean up. the updated README at root has the steps, but you could give this a try: `make clean && make reset && make build && make start`. this should set all the containers up, including the `ui`, which can be accessed at `localhost:3000`. Few key points:
- there is a general case of a race condition amongst containers, which could cause come containers to begin "pre-maturely". an existing issue for health-checks is addressing this concern.
- to the point on using a better backend language, agreed it would better to handle system interaction processes using golang or rust or even swift for that matter. the choice of NodeJS was to provide a good runtime for wrapping through the different system calls and enabling easy web service connectivity. Specifically, the interaction with zkp (ZoKrates) service which uses Rust in the backend anyway. 
- The issue with performance is understood and there are ongoing efforts to help mitigate this with a better system integration architecture. Using multi-stage builds is also a consideration here. In terms of memory and storage consumption, we do note that the zkp aspects of the system do incur a compute cost, and are looking into options/variations of tooling, substitutions, or directly interacting with the underlying libraries as native calls to the containers, instead of wrapping `cli` calls. We are very much encouraging the community to step in as they seem fit and usable.
If you have any specific areas that you'd like to point out, where one could supplement the backend with Go/Rust as needed, that would be helpful to further identify/work toward resolving the concern.
thanks @Mel-Marsollier for helping through this process.

**Comment by jeffprestes** [comment]
Thanks @Mel-Marsollier and @skarred14 
So, I could move forward and now Radish starts. Great achievement.
However, the URL: http://localhost:3000/products returns HTTP 404. I don't now if this item is under development but I thought you would know this.
Please let me know if this item is under development because if so I will close this issue.
Kind regards.

**Comment by jeffprestes** [comment]
And congratulations for create makefile scripts. They make our life much easier.

**Comment by Mel-Marsollier** [comment]
Hi Jeff, 

Last time I checked there was still a bit of work to be done in transitioning the way that organizations and their related partner status are being called on. Short answer yes! The logic is being rework at the moment. 

Happy to use this thread and let you know when it's done. And thank you for the multiple instances of your constructive feedback on the project - you are a great extra eye to have around.

**Comment by breakpointer** [comment]
Thanks all for your comments and help! This issue seems resolved so I am closing it now.
