### ISSUE TITLE
Radish34 Setup steps in README fail

### ISSUE THREAD

**Issue by MCLDG** [ethereum-oasis/baseline#112]
## Expected Behavior
The steps in the Radish README should complete successfully. Specifically, this step should succeed: `npm i && npm run postinstall`

## Actual Behavior

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ npm i && npm run postinstall
npm WARN radish-34@1.0.0 license should be a valid SPDX license expression

audited 884760 packages in 6.363s
found 0 vulnerabilities

npm ERR! missing script: postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/edgema/.npm/_logs/2020-04-16T08_45_46_534Z-debug.log
```

Next error:
```
$ npm run build:contracts

.
.
.
> sol-compiler

sh: sol-compiler: command not found
```

## Steps to Reproduce the Problem

  1. Clone the repo
  1. Follow the pre-requisites in the Radish README
  1. Execute steps under Setup

## Specifications

  - Version: 
  - Platform: Mac
  - Subsystem: 10.14.6

**Comment by kthomas** [comment]
@MCLDG try the top-level readme steps. It is an oversight that the radish34 readme does not match the steps outlined in top-level readme. Use `make && make start`.

**Comment by MCLDG** [comment]
Thanks @kthomas , you're right, `make` works fine. And it's much faster than it was - kudos for that. Is there a plan to update the docs?

**Comment by sampsojp** [comment]
Just in case this might help someone else - I had problems installing with make due to issues around pushd. I run on WSL2 so seems to be some complication with the path. Not sure. After a bit of trial and error I was able to get the app running with the following steps...
1. In radish34 run npm i
2. Run npm ci in sub-dirs: messenger, api, deploy, ui, zkp, contracts
3. In radish34 run docker-compose build
4. In radish34 run npm setup-circuits
5. In radish34 run npm run install-config (this one isn't documented in the radish34 readme but based on info in step 6 it looked like it needed to be run)
6. In contracts run npm run build
7. In radish34 run npm run deploy
8. In radish34 run docker-compose up -d && docker-compose restart
9. In radish34 run integration tests: npm run test
10. UI accessible at http://localhost:3000

**Comment by kthomas** [comment]
Thanks @sampsojp and good to hear @MCLDG.

I have a branch that fixes the make targets for Linux env. Will be opening a PR shortly if you wouldn't mind testing 👍

**Comment by sampsojp** [comment]
Would be happy to. :-)

**Comment by kthomas** [comment]
@sampsojp see #125

**Comment by sampsojp** [comment]
> @sampsojp see #125

Thanks kt. I'm full today with day job but will get to this tonight. Really appreciate your work on this.

**Comment by sampsojp** [comment]
> @sampsojp see #125

make && make start && make test worked perfectly on Ubuntu. Thanks!

**Comment by MCLDG** [comment]
As a bonus, make && make start && make test works perfectly on Amazon Linux too, just tested it.
