### ISSUE TITLE
Custom Template Integration

### ISSUE THREAD

**Issue by alejandroballestae** [ethereum-oasis/baseline#143]
Hi, 

Im trying to integrate a react template that depends on node-sass to work. When I install node-sass and I start the project it shows me this error:

./src/components/ItemDetails/style.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/components/ItemDetails/style.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.

In this case, ItemDetails is the component of my template and it seems that is not working becouse it cant load the 'scss' extension.

The component is installed under radish34/ui/components and in the node_modules I do see the node-sass installed.

Do you know what is the node-sass missing even I already installed?

Thanks!
BR.

**Comment by breakpointer** [comment]
Hi @alejandroballestae I'm not sure I follow because I do not typically do front-end work. But it sounds like it's not on the load path when you're running your code. 🤷 Try `rm -rf` of your node_modules and re-install?

Also, since this is an issue with code you're working on and not the baseline code I'm going to close this. If you're still having issues [please join the Baseline slack channel and we can discuss.](https://join.slack.com/t/ethereum-baseline/shared_invite/zt-d6emqeci-bjzBsXBqK4D7tBTZ40AEfQ)

**Comment by alejandroballestae** [comment]
Hi,

We found the solution, we had to add the package on deploy node_modules and
also in ui node_models. After restart the docker.

Thanks for your help.
BR.
